server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-braker
          uri: https://github.com/SebastianLedesma/microservice2023
          search-paths: config-data
  application:
    name: config-service